### ISSUE TITLE
Compilation of documentation with MyST on readthedocs

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#101]
Following issue #84 and the introction of MyST (commit 565f2ce), it seems that the documention no longer compiled: https://readthedocs.org/projects/buildh/builds/13803288/. The error message is `no theme named 'sphinx_book_theme' found (missing theme.conf?)`. This pb does not appear locally.
Another weird thing, on the main page https://readthedocs.org/projects/buildh/, there is a version called [fix-readthedocs-sphinx-book-theme](https://buildh.readthedocs.io/en/fix-readthedocs-sphinx-book-theme/) which is not the latest or stable version but for which the compilation is OK. This name looks like a commit or PR title.

**Comment by patrickfuchs** [comment]
OK now I understand, `fix-readthedocs-sphinx-book-theme` is the name of a new branch you just created 😉 !

**Comment by pierrepo** [comment]
Hello @patrickfuchs 
Yes, `fix-readthedocs-sphinx-book-theme` is a new branch to try to fix this issue.
But the work is still in progress...

**Comment by patrickfuchs** [comment]
At least I see the right layout of MyST 😄

**Comment by patrickfuchs** [comment]
Hi @pierrepo, could you find a solution to that issue? Shall I wait for this issue to be solved before releasing a new version?

**Comment by patrickfuchs** [comment]
Great it works now 👍
