### ISSUE TITLE
JOSS paper

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#109]
Hello there, I put a first version of the paper in the dir `paper`. I have to work on it a bit and then I make you know once you can have a look and amend it.

**Comment by patrickfuchs** [comment]
After b90d3a2, I think the paper is ready for your review. Maybe reading this before would be good: https://joss.readthedocs.io/en/latest/submitting.html
I only included sections `Statement of need` and `Overview` but not `Summary` or `Background` because I thought it'd be redundant. While you read that, I try to finish the last small details.

**Comment by HubLot** [comment]
> I only included sections Statement of need and Overview but not Summary or Background because I thought it'd be redundant
By reading the `submitting` section, it looks like to me that the `Summary` is mandatory, no ? (see here also : https://joss.readthedocs.io/en/latest/review_checklist.html)

**Comment by patrickfuchs** [comment]
> By reading the `submitting` section, it looks like to me that the `Summary` is mandatory, no ? (see here also : https://joss.readthedocs.io/en/latest/review_checklist.html)

I think they don't talk about the section `Summary` itself. If we look at the following sentence: *Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?* 
To me there is such a description in the section `Overview`. By looking at some examples of published papers in JOSS, many of them don't have a section `Summary`. For example, Pierre's [paper on Autoclass](https://joss.theoj.org/papers/10.21105/joss.01390) doesn't have one. @pierrepo what do you think?

**Comment by pierrepo** [comment]
I don't think we need a summary, although me might create a `Background` section with the first part of `Statement of need`.

**Comment by HubLot** [comment]
okay my bad then. I was looking some examples too and they all have the `summary` section :D

**Comment by patrickfuchs** [comment]
> I was looking some examples too and they all have the summary section

Bad luck 😉 

> I don't think we need a summary, although me might create a Background section with the first part of Statement of need.

I like the idea of adding a `Background` section before `Statement of need`. This latter section could start by the sentence *It is pretty easy to reconstruct Hs from the heavy atoms using standard geometric rules respecting stereochemistry.* I also propose to change this last sentence  to *Reconstructing Hs from the heavy atom coordinates can be done using standard geometric rules respecting stereochemistry.*.

**Comment by patrickfuchs** [comment]
@pierrepo, I merged PR #114 from @HubLot, so you can go ahead if you want to propose some modifications on the paper. Thanks!

**Comment by patrickfuchs** [comment]
Thanks for your contribution @pierrepo. I think we are fine now, there are only a few question marks to replace once we have the version number and the sfw number. I think we can close this issue if you agree!

**Comment by patrickfuchs** [comment]
Wait... last minut little thing to do: I have to add a ref to the NMRlipidsIVb project using the DOI link to the Zenodo archive for paper: https://doi.org/10.5281/zenodo.4748646 (the paper is under revisions).

**Comment by patrickfuchs** [comment]
Done in a0b3cd6. This was important to add NMRlipids IVb and the Databank refs since these are the projects that use buildH! So I can now close this issue.
