### ISSUE TITLE
Implement -b -e flags to select different slices of a trajectory

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#11]

**Comment by HubLot** [comment]
I started to look into it. It's not so trivial.
Should we use a gromacs-like slicing with time frame (from 1000ps to 2000ps) or MDAnalysis-like with the number of the frame (from frame 10 to frame 20) ?
The latter is simple : we just need to check the range and give it to MDAnalysis.
The former is more intuitive but more complicated. We have to do a bit of calculations to go from "frame 1000ps" to the actual number of frame corresponding to 1000ps regarding the "dt"

**Comment by patrickfuchs** [comment]
Following our discussion, it is more useful to give `-b` and `-e` in units of time rather than frame numbers. We can get the the starting time of the traj with `u.trajectory.time` (assuming `u` is a MDAnalysis universe) before looping on it, and the step between frames with `u.trajectory.dt`. So we also need to check whether the `-b` and `-e` values given by the user make sense with respect to the traj.

**Comment by HubLot** [comment]
I started working on it.
You can view the progress here: https://github.com/HubLot/buildH/tree/slice
Once it's mature, i'll make a PR
