### ISSUE TITLE
Bug in hierarchical organization of items in doc

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#112]
In the right menu in the doc, `User manual`, `Tutorials` sections appear as subsections of `Licence`:

![image](https://user-images.githubusercontent.com/733861/121906817-c528b800-cd2b-11eb-990e-1a0a053373ce.png)

![image](https://user-images.githubusercontent.com/733861/121906757-b5a96f00-cd2b-11eb-92e7-100a395144ad.png)

Is this really intended?

**Comment by patrickfuchs** [comment]
Good catch @pierrepo, I didn't realize this! This comes after the doc re-organization proposed by @HubLot. I think it was not intended 😉

**Comment by HubLot** [comment]
oops
