### ISSUE TITLE
Add community guidelines

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#116]
According to JOSS [Review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html)

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

We should add in the documentation clear guidelines on contribution and bug report.
A `CONTRIBUTING.md` file in the repo could also help (see [example](https://github.com/pierrepo/autoclasswrapper/blob/master/CONTRIBUTING.md))

**Comment by patrickfuchs** [comment]
Very good idea 👍
