### ISSUE TITLE
Add `-v` and `--version` options

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#119]
For reproducibility, it's often useful to output the version of the tool we use.

It might be pertinent for `buildH` to provide its version as well. For instance:
```
$ buildH -v
1.3.1
$ buildH --version
1.3.1
```

**Comment by patrickfuchs** [comment]
Yes, very good idea 👍 Someone has time to implement this option?

**Comment by pierrepo** [comment]
I'll try something.
