### ISSUE TITLE
Force python 3 detection

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#12]
I realized that when installing MDAnalysis with python2.7, buildH doesn't issue any error but when it runs, it generates wrong results. So we should add a detection of python 3.7 (or higher).

**Comment by patrickfuchs** [comment]
Done in 6bc8c68! Question to @HubLot and @pierrepo, in this [line](https://github.com/patrickfuchs/buildH/blob/6bc8c68162fb6c94ecfa99ef80ce98051977e10a/buildH_calcOP.py#L1089) I use the Exception UserWarning. Do you think it is the most appropriate?

**Comment by pierrepo** [comment]
`UserWarning` seems OK to me.
But i'll advise to check strickly for Python >= 3.6 since f-string are a really nice feature.

**Comment by HubLot** [comment]
Seems good to me too.
But do you have a reason to restrict to Python >= 3.7 (or even 3.6) ? 3.5 is still maintained for a year for example (https://devguide.python.org/#branchstatus)

By the way, @patrickfuchs you removed the '#' in the first line of the script so it doesn't work anymore :D  : https://github.com/patrickfuchs/buildH/blob/6bc8c68162fb6c94ecfa99ef80ce98051977e10a/buildH_calcOP.py#L1

**Comment by patrickfuchs** [comment]
Thanks guys for your answer 😄 ! For the version, it looks like 3.6 could be a good compromise, this could allow us to use f-strings indeed. Thanks also @Hublot for reporting the mistake on line 1, I was too tired yeasterday evening 😉.

**Comment by pierrepo** [comment]
It looks like the detection of the Python version is not present in the code anymore.

In addition, by using a Python package, `setup.cfg` enforces Python >= 3.6

We could close this issue.
