### ISSUE TITLE
Add link to doc in the upper right corner of the GitHub page

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#125]
We can add a link to the doc in the project description in the upper-right corner of the GitHub page.

To do so, click on the gear (only visible to you @patrickfuchs):

![image](https://user-images.githubusercontent.com/733861/122688937-ab9dd980-d21f-11eb-8b4e-f93960fa707a.png)

In the Website field, add `https://buildh.readthedocs.io/`

You can also uncheck boxes `Packages` and `Environments`

**Comment by patrickfuchs** [comment]
Thanks @pierrepo. I tried, but the field *Website* is in gray and I can't modify it. Do you know how to change this?

**Comment by pierrepo** [comment]
No idea. It works out of the box for me :thinking:

**Comment by patrickfuchs** [comment]
I  tried to search a bit, but found nothing interesting... In all examples, the Website can be changed, but in my case it's gray and I cannot edit it:

![website](https://user-images.githubusercontent.com/13885052/123091509-b926af80-d429-11eb-8d6d-ad66c9649c40.png)

Maybe something is checked somewhere which induces this behavior? Any idea @HubLot ?

**Comment by HubLot** [comment]
you sure that when you click inside it you can't edit it? 
Because I have the same behavior on the fork (or others repos) but I can click inside and modify it.

**Comment by patrickfuchs** [comment]
Yes I am. For you, does it appear in black?

**Comment by HubLot** [comment]
No, it appears like you :/

**Comment by pierrepo** [comment]
I think we will have to check this with you during a visio @patrickfuchs

**Comment by patrickfuchs** [comment]
My bad, in fact it works very well and I can edit it, sorry :sweat_smile: !!! In fact, I was trying to select some text within that box using my mouse, this doesn't work. But if I type something it works 🎉
