### ISSUE TITLE
Update MDAnalysis to 1.1.1

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#134]
In PR #130, we considered updating MDAnalysis to version 1.1.1. Someone has time to look at that?

**Comment by pierrepo** [comment]
Interestingly, MDAnalysis 1.1.1 is [incompatible](https://github.com/MDAnalysis/mdanalysis/releases/tag/release-1.1.1) with Python 3.9.

By default, my conda envs have Python 3.9 by default, and the only compatible MDAnalysis version is 1.0.0 that produces that many warnings.

To force Python 3.8, here was I did:
```
$ conda env remove -n buildh
$ mamba create -n buildh python=3.8
$ mamba env update -f binder/environment.yml
$ conda activate buildh
$ python --version
Python 3.8.10
$ conda list | grep mda
mdanalysis                1.1.1                    pypi_0    pypi
```
For Python 3.8, the default MDAnalysis version is the latest, i.e. 1.1.1 :+1: 

From `Notebook_02_buildH_calc_OP_outputwH.ipynb`, I got:
```
!buildH -c start_128popc.pdb -l Berger_POPC -t popc0-25ns_dt1000.xtc -d Berger_POPC.def -o OP_POPC.dat -opx traj_POPC_wH

Constructing the system...
/home/pierre/.soft/miniconda3/envs/buildh/lib/python3.8/site-packages/MDAnalysis/coordinates/XDR.py:216: UserWarning: Reload offsets from trajectory
 ctime or size or n_atoms did not match
  warnings.warn("Reload offsets from trajectory\n "
System has 28526 atoms
Writing new pdb with hydrogens.
Writing trajectory with hydrogens in xtc file.
/home/pierre/.soft/miniconda3/envs/buildh/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py:865: UserWarning: Reader has no dt information, set to 1.0 ps
  warnings.warn("Reader has no dt information, set to 1.0 ps")
Dealing with frame 0 at 0.0 ps.
/home/pierre/.soft/miniconda3/envs/buildh/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py:865: UserWarning: Reader has no dt information, set to 1.0 ps
  warnings.warn("Reader has no dt information, set to 1.0 ps")
Dealing with frame 1 at 1000.0 ps.
Dealing with frame 2 at 2000.0 ps.
Dealing with frame 3 at 3000.0 ps.
Dealing with frame 4 at 4000.0 ps.
Dealing with frame 5 at 5000.0 ps.
Dealing with frame 6 at 6000.0 ps.
```

This looks much better. We should be able to solve the warning `warnings.warn("Reader has no dt information, set to 1.0 ps")`.

Should we limit buildH to Python 3.6, 3.7 and 3.8 (at least until MDAnalysis supports Python 3.9)?

**Comment by patrickfuchs** [comment]
Thanks @pierrepo ! This is indeed much better 😄 Indeed we can stay at Python 3.8 for now, this won't change anything for buildH.
I think you won't have the `warnings.warn("Reload offsets from trajectory\n ")` if you delete the tmp files created by MDAnalysis `.*.npz`. There's probably a mismatch of version or system if one such file was present in your dir. Could you give it a try?
Regarding `warnings.warn("Reader has no dt information, set to 1.0 ps")`, this is weird because we do have the time stamps (since buildH print them to the screen!). Maybe there's a way also to get rid of those warnings (by calling some functions with an extra argument)? I can have a look tomorrow.

**Comment by patrickfuchs** [comment]
Just tried the Berger test case in a terminal:

```
$ buildH -c start_128popc.pdb -t popc0-25ns_dt1000.xtc -l Berger_POPC -d ../../def_files/Berger_POPC.def
Constructing the system...
System has 28526 atoms
Dealing with frame 0 at 0.0 ps.
Dealing with frame 1 at 1000.0 ps.
[...]
Dealing with frame 24 at 24000.0 ps.
Dealing with frame 25 at 25000.0 ps.
Results written to OP_buildH.out
```

No warning at all 😎

**Comment by patrickfuchs** [comment]
I tried a Notebook with prior removing of `.*.npz` file:

```
!buildH -c start.gro -l Berger_POPC -t md_0_25ns_dt1000.xtc -d Berger_POPC.def -o OP_POPC.dat -opx traj_POPC_wH

Constructing the system...
System has 46600 atoms
Writing new pdb with hydrogens.
Writing trajectory with hydrogens in xtc file.
/home/fuchs/software/miniconda3/envs/buildh/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py:865: UserWarning: Reader has no dt information, set to 1.0 ps
  warnings.warn("Reader has no dt information, set to 1.0 ps")
Dealing with frame 0 at 0.0 ps.
/home/fuchs/software/miniconda3/envs/buildh/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py:865: UserWarning: Reader has no dt information, set to 1.0 ps
  warnings.warn("Reader has no dt information, set to 1.0 ps")
Dealing with frame 1 at 1000.0 ps.
Dealing with frame 2 at 2000.0 ps.
[...]
```
I get rid of the first warning `warnings.warn("Reload offsets from trajectory\n ")`, but the other ones about `dt` are still there. I don't understand why we get them within the Notebooks and not in a Unix shell... Any idea?

**Comment by pierrepo** [comment]
This is really weird. Are you sure you were in the same conda env?

**Comment by patrickfuchs** [comment]
> This is really weird. Are you sure you were in the same conda env?

Yes... What is even weirder:

**Comment by HubLot** [comment]
I think it's due to the option to *write* xtc and pdb files no?

**Comment by patrickfuchs** [comment]
Well spotted  @HubLot, I've been too fast! Indeed they appear only if we use `-opx` option to write the traj with H.

**Comment by patrickfuchs** [comment]
We just talked with @HubLot and found the solution. When we create the Universe with H, we do it initially with a single PDB, thus it has no dt info. When we write the new traj (with the xtc writer) this is there where MDAnalysis throws a warning. The solution, is to add the dt info of the Universe without H at the time when we create the Universe with H. Speedy @HubLot has already proposed a PR to fix this 😄 👍

**Comment by patrickfuchs** [comment]
The merge of PR#136 didn't close this issue, so I do it manually.
