### ISSUE TITLE
Restrict BuildH for Python >= 3.6 and <= 3.8

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#137]
Due to the limited availability of MDanalysis for Python <= 3.8 (see issue #134), we should also restrict buildH for Python <= 3.8.

**Comment by pierrepo** [comment]
According to the [documentation](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires), we should replace 
```
python_requires= >=3.6
```
by
```
python_requires= >=3.6 <=3.8
```
in `setup.py`.

**Comment by patrickfuchs** [comment]
Would that better go in `setup.cfg` ?

**Comment by pierrepo** [comment]
Yes, of course, in `setup.cfg` ;-)
