### ISSUE TITLE
Use logging module

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#14]
For this kind of project, I'll advise to use the `logging` module instead of the `print()` function.

You will find here a small example : https://github.com/pierrepo/seq-to-first-iso/blob/master/seq_to_first_iso/seq_to_first_iso.py
First, import the module: 
```
import logging
```
Then configure it:
```
# Set custom logger.
log = logging.getLogger(__name__)
log_handler = logging.StreamHandler()
log_formatter = logging.Formatter("[%(asctime)s] %(levelname)-8s: %(message)s",
                                  "%Y-%m-%d, %H:%M:%S")
log_handler.setFormatter(log_formatter)
log.addHandler(log_handler)
log.setLevel(logging.INFO)
```
Note that with `logging` you have the ability to print messages in the console and save them in a log file in the mean time (with just a few lines of extra configuration)!

The use it:
```
log.info("This an info message")
log.warning("This is a warning message")
log.error("This an error massage")
log.critical("This an error message that will stop the program!")
```

**Comment by pierrepo** [comment]
And we will be able to replace these lines while keeping the ability to be verbose on debug:
```
# For debugging.
# TODO: Remove it after implement logging feature
DEBUG=False
```

**Comment by patrickfuchs** [comment]
OK great! So we just as to use this `log.something()`  instead of all the `print()` we have in the code. Quick question, how do we pass this log object when we have multiple modules?

**Comment by pierrepo** [comment]
logging instances are automatically attached to the main module.
Here what you could declare in the main (`__init__.py`) module (see for instance [here](https://github.com/pierrepo/autoclasswrapper/blob/master/autoclasswrapper/__init__.py)):
```
import logging

log = logging.getLogger(__name__)
log_handler = logging.StreamHandler()
log_formatter = logging.Formatter("%(asctime)s %(name)s %(levelname)-8s %(message)s",
                                  "%Y-%m-%d %H:%M:%S")
log_handler.setFormatter(log_formatter)
log.addHandler(log_handler)
log.setLevel(logging.INFO)
```

and in your submodule (see also example [here](https://github.com/pierrepo/autoclasswrapper/blob/master/autoclasswrapper/output.py)):
```
import logging
log = logging.getLogger(__name__)

log.info("Hello")
log.warning("Warning!")
```

We could also define the log level with an option from the command line. See for instance [here](https://docs.python.org/fr/3/howto/logging.html#logging-to-a-file).

**Comment by pierrepo** [comment]
One could also force log level through env variable:
```
import logging
import os

log = logging.getLogger(__name__)
log_handler = logging.StreamHandler()
log_formatter = logging.Formatter("%(asctime)s %(name)s %(levelname)-8s %(message)s",
                                  "%Y-%m-%d %H:%M:%S")
log_handler.setFormatter(log_formatter)
log.addHandler(log_handler)

level = os.environ.get("LOGLEVEL", "INFO")
if level in ["DEBUG", "INFO","WARNING", "CRITICAL", "ERROR"]:
    log.setLevel(level)
else:
    log.setLevel(logging.INFO)
```
That would probably be easier.

**Comment by HubLot** [comment]
wont be implemented
