### ISSUE TITLE
[Request] Add documentation for building from source with minimal dependencies

### ISSUE THREAD

**Issue by lilyminium** [patrickfuchs/buildH#144]
1. The current documentation for building from source starts here: https://buildh.readthedocs.io/en/latest/installation.html#for-developpers

(typo note: developpers -> developers, developement -> development)

2. Which links to this fairly complete document on how to install via conda with an environment file: https://github.com/patrickfuchs/buildH/blob/master/devtools/install_dev.md

(suggestion: I'd say "building from source" at some point for people googling)

However, I'm not sure I actually need any of the stuff in `environment.yml` apart from the link to `requirements.txt`. `pytest`, `sphinx`, etc are helpful if I want to make a development environment, but not necessary to just build the package from source and run it.

**Request:**

Add an explicit link to `requirements.txt` in the user-facing documentation with instructions for how to use it. This has the advantage of also documenting installing with pip, as some people can't or won't use conda. It also more explicitly fulfills the JOSS requirement for installation instructions "Is there a clearly-stated list of dependencies?".

**Comment by patrickfuchs** [comment]
Thanks very much @lilyminium for your suggestion.

Indeed I understand your point. In commit ad89bf3, I corrected the typos and created a new section `Building from source` in the [installation page](https://buildh.readthedocs.io/en/latest/installation.html), which explains how to build from source without installing the full dev environment.

Regarding the JOSS requirement "Is there a clearly-stated list of dependencies?", in the main [README](https://github.com/patrickfuchs/buildH/blob/master/README.md), there is a section called "Requirements" which clearly states the packages needed (and Python versions) to run buildH. Now it is also written in the [installation page](https://buildh.readthedocs.io/en/latest/installation.html) of the doc.

**Comment by patrickfuchs** [comment]
For some reason the build-documentation github action didn't work (although it did in July!), so you can check the update doc page [here](https://github.com/patrickfuchs/buildH/blob/master/docs/installation.md) for now. I will try to solve this action ASAP, but I may need my colleague @pierrepo who is currently on vacation.

**Comment by patrickfuchs** [comment]
I could fix the doc compilation in commit 7441be9. Now the section *Building from source* is readable in the doc page: https://buildh.readthedocs.io/en/latest/installation.html#building-from-source.

**Comment by lilyminium** [comment]
Thank you!
