### ISSUE TITLE
Fixing box dimensions and trajectory output with Hs

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#145]
In PR #142, this line proposed a way to write box dimensions in the xtc: 
https://github.com/patrickfuchs/buildH/blob/1a2c740136910b3293dde395cb37e76ecb566454/buildh/core.py#L649

Unfortunately, for some reason, it *rewinds the trajectory* to the first frame so that the newly built xtc with Hs gets the same (first) frame written at each iteration of the loop!!!
In commit d5a35c4, I fixed that with 

```
universe_wH.trajectory.ts.dimensions = ts.dimensions
```

which avoids this rewind. I also added box dimensions in the generated pdb with Hs + a remark in case no unitcell info was present in the input pdb.

The commit above should fix this issue, but I leave it open until you (@HubLot & @pierrepo) are back from vacation, so you can have a look 😄.

**Comment by patrickfuchs** [comment]
I also added some tests (commit ac6303d) to check the integrity of the newly generated pdb and xtc with Hs.

**Comment by richardjgowers** [comment]
@patrickfuchs just to clarify this behaviour.  MDAnalysis only holds a single frame in memory at any time (with memoryreader being the exception) `u.trajectory[n]` is the syntax for loading frame `n` of a trajectory.  It's worth noting that changes to `.dimensions` / `.positions` won't be persistent if you move between frames.  Let me know if you have any more questions on this behaviour.

**Comment by patrickfuchs** [comment]
Thanks very much @richardjgowers for this clarification, this is very useful. We made the change using the syntax `u.trajectory[n]` just before submission (to avoid some warnings from MDAnalysis), but were not aware of this behavior. I think now we are fine.

**Comment by HubLot** [comment]
well spotted @patrickfuchs! 
I don't understand how the previous code was supposed to work now I see the fix...
This bug,  by itself, should trigger a minor version upgrade.
