### ISSUE TITLE
Which three things? (docs)

### ISSUE THREAD

**Issue by lilyminium** [patrickfuchs/buildH#146]
Contributing.md starts off with:
> 
> First, thank you for contributing!
> 
> Before starting, you should read, agree to, and follow these three things:
> 
>     Contributing Guidelines
>         How to contribute?
>             Report bugs
>             Submit feedback
>         Pull Request Guidelines

I think perhaps the "follow these three things" belongs further down the page?

**Comment by patrickfuchs** [comment]
I corrected the sentence and the menu in 4dbe4a8, one item was missing.

**Comment by lilyminium** [comment]
Thank you!
