### ISSUE TITLE
Add a message that PBC are not taken (yet) into account

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#15]
After a discussion with Hanne Antila, it looks like we can obtain "funny" results when the molecules are not whole (as produced by mdrun). So for now, it's probably useful to warn the user that he/she shall use trajectories with whole molecules (produced with `trjconv` with flag `-pbc mol`. In the future we can think about supporting molecules split at the boundaries. But this is low priority.

**Comment by HubLot** [comment]
Maybe the best place is to put on the README ?

**Comment by patrickfuchs** [comment]
This issue should have been close with commit a296866 (I made a typo in the message with issue number 🤣)
