### ISSUE TITLE
Beta hydrogens in PS

### ISSUE THREAD

**Issue by ohsOllila** [patrickfuchs/buildH#159]
When adding united atom simulation data into the NMRlipids databank, we noticed with @larabort that beta hydrogens in POPS headgroups in Berger and Gromos have a type of "CHdoublebond":
https://github.com/patrickfuchs/buildH/blob/master/buildh/lipids/Berger_POPS.json
https://github.com/patrickfuchs/buildH/blob/master/buildh/lipids/GROMOSCKP_POPS.json

I am not sure, but my feeling is that "CH" and addition of nitrogen atom in the list would be more appropriate.
What do you think?

**Comment by patrickfuchs** [comment]
Thanks for the comment @ohsOllila, I think you're right. We'll correct that as soon as we can.

**Comment by patrickfuchs** [comment]
I just checked, indeed this carbon should be a CH with the three helpers that include the neighboring nitrogen.
