### ISSUE TITLE
Latex formulas are not rendered correctly on readthedoc

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#165]
The formulas written in Tex are not rendered properly on readthedoc, for example `$\theta$` is printed instead of the greek letter in the [page describing the algorithms](https://buildh.readthedocs.io/en/latest/algorithms_Hbuilding.html)). @pierrepo do you know how to fix this?

**Comment by pierrepo** [comment]
Don't know. Maybe an extension to activate with ReadTheDocs? @HubLot any idea?

**Comment by HubLot** [comment]
after a little digging, we need to activate the extension in the new version of myst

**Comment by patrickfuchs** [comment]
Yes 😎 !

![maths_OK](https://user-images.githubusercontent.com/13885052/208693638-83b97339-02ad-4f8e-a472-1f01011b2f6d.png)
