### ISSUE TITLE
Add Zenodo description file

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#27]
Zenodo can be used to archive buildH source code.

Zenodo metadata can be defined in a file called `.zenodo.json`. Here's an example: https://github.com/pierrepo/autoclasswrapper/blob/master/.zenodo.json

For buildH, we need:

- [x] a title
- [x] author's ORCID
- [x] some keywords

**Comment by pierrepo** [comment]
@patrickfuchs is 
>Build hydrogens from a united-atom MD of lipids and calculate the order parameter

an appropriate title?

**Comment by patrickfuchs** [comment]
Well, I agree it's long, but at least it says what if does. I thought the title was `buildH` (repo name) and that this line was a short description. Seems like I'm wrong, Am I?

**Comment by pierrepo** [comment]
No. The description you provided seems accurate and fine to me.

I just wanted to be sure.

**Comment by pierrepo** [comment]
@HubLot @patrickfuchs and @ABacle could you please provide me your [ORCID](https://orcid.org/)?

If you don't have such identifier, could you please [create one](https://orcid.org/register)?

**Comment by HubLot** [comment]
Here's mine : https://orcid.org/0000-0001-6149-9480

**Comment by patrickfuchs** [comment]
Here's mine : https://orcid.org/0000-0001-7117-994X

**Comment by pierrepo** [comment]
@ABacle could you please provide me your ORCID or create one if needed (https://orcid.org/register)?

**Comment by ABacle** [comment]
Here is my ORCID number : 0000-0002-3317-9110

**Comment by pierrepo** [comment]
Thank you @ABacle  :+1:
