### ISSUE TITLE
Install bumpversion to update easily version number

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#28]

**Comment by patrickfuchs** [comment]
Very good suggestion. So far I just used `git tag`.

**Comment by HubLot** [comment]
Bump version is not maintained anymore:  https://github.com/peritus/bumpversion
But there is some alternatives : [bump2version](https://github.com/c4urself/bump2version/) which is a fork or [python-versioneer](https://github.com/python-versioneer/python-versioneer) but seems more complicated.

**Comment by pierrepo** [comment]
Thanks @HubLot 
`bump2version` looks very nice and compatible with older `bumpversion` config file

**Comment by patrickfuchs** [comment]
Now that the tests are completed, that would be nice to at least add a tag and upgrade the version number (from 1.0.3 to 1.0.4). Regarding bump2version, I never used it, is it fast to implement? Shall I add a tag, or we wait for the bump2version implementation, what do you suggest?

**Comment by pierrepo** [comment]
bump2version adds a tag automatically. I can have a look tomorrow morning.
