### ISSUE TITLE
Remove template tag from repo

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#32]
This repo appears as a *template*:
![image](https://user-images.githubusercontent.com/733861/102886265-17f87580-4455-11eb-8e0b-df776b1ec438.png)

There is no reason for this. @patrickfuchs could you please remove this in the settings?
![image](https://user-images.githubusercontent.com/733861/102886394-4d9d5e80-4455-11eb-951e-441467b8c12e.png)

**Comment by patrickfuchs** [comment]
Done! I think it was set by default when I created the repo. At that time, I didn't know the meaning of this 😉
