### ISSUE TITLE
Create doc

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#35]
I'm about to create a `doc` dir. I'll move there all the stuff related to doc (`vectors.png`, `CHARMM36_POPC_validation`), simplify the main `README.md` by move some of its content.
Once done, we can complete later the doc in a some appropriate format (sphynx?) and add notebooks to guide the user.

**Comment by pierrepo** [comment]
Great!
`docs` with an *s* is more usual.

**Comment by patrickfuchs** [comment]
Oops sorry, just renamed it 😄 !

**Comment by patrickfuchs** [comment]
Hey @pierrepo, looking at https://github.com/pierrepo/PBxplore, I see it's called `doc` there. Any comment?

**Comment by pierrepo** [comment]
Yep. It was an old projet (same for autoclasswrapper). I now tend to have `tests`, `docs`, `notebooks` and `devtools`, all with *s*

**Comment by patrickfuchs** [comment]
I'm cleaning up the directory `Berger_POPC_test_case`, there are several files there. I think I should tidy up the files with extensions `apineiro_style.out` or `jmelcr_style.out`. Since the code now only generates one style, I'll keep that one.

**Comment by pierrepo** [comment]
@patrickfuchs could you please create yourself an account on [ReadTheDocs](https://readthedocs.org/accounts/signup/)?
- I advise you to sign up with your GitHub account. It will ease this import of your project.
- Once connected, click on "Import a project", select buildH repo and click on the "+" button
- Then, on the projet itself, click on "Admin" and then "Maintainers". At this point could you add Hubert (`Hub_lot`) and myself (`pierrepo`)?

**Comment by patrickfuchs** [comment]
Thanks @pierrepo ! Here's the URL: https://readthedocs.org/projects/buildh/ and I added you as maintainer.
@HubLot: I couldn't add you as maintainer, I guess you have to create an account on readthedocs?

**Comment by pierrepo** [comment]
@patrickfuchs 

Adding `Hub_lot` worked for me: https://readthedocs.org/profiles/Hub_lot/

**Comment by HubLot** [comment]
thanks!

**Comment by patrickfuchs** [comment]
The problem was the underscore !
