### ISSUE TITLE
Improve PEP 257 compliance.

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#39]
We should improve docstrings [PEP 257](https://www.python.org/dev/peps/pep-0257/) compliance. Especially for [one-line docstrings](https://www.python.org/dev/peps/pep-0257/#one-line-docstrings).

We could use `pydocstyle` for this. `pydocstyle` is already installed in the conda environement (see `binder/environment.yml`).

**Comment by patrickfuchs** [comment]
I'd say that https://python.sdv.univ-paris-diderot.fr/15_bonnes_pratiques/#152-les-docstrings-et-la-pep-257 is worth a read 😉 
Note: since the beginning, I decided to use the *NumPy* style for docstrings.
I can also clean them up, so I also assigned myself to this issue.
