### ISSUE TITLE
Transform dic_lipids.py into json files

### ISSUE THREAD

**Issue by HubLot** [patrickfuchs/buildH#48]
After thorough discussion, it will be better to transform the `dic_lipids.py` into json files.
This `dic_lipids.py` is used to reconstructed hydrogens from a united atom bilayer.

This will allow the users to add their own .json files for their own trajectories. 
A regular database of json will be created in the buildH source code into a directory called `lipids` to provide a set of supported lipids.
We will add an option to the program for user to provided their own json.

Steps:
- [x] Convert the current dic_lipids.py into a series of .json files into `buildh/lipids` directory
- [x] Transform the code to read those json files
- [x] Provide a list of supported lipids when using the `-h` of the program (by parsing the directory)
- [x] Add an argument for users to provide their own .json files.
- [ ] Integrate the lipids from https://github.com/NMRLipids/buildH/commit/d0a2bc1b31f59e32032e84c6802404e9b540b48c (issue #44)

**Comment by patrickfuchs** [comment]
I reopen this issue because we're not done yet. I checked what's been done above. I think the most urgent thing is to implement *Provide a list of supported lipids when using the `-h`*. We can discuss it this afternoon.

**Comment by HubLot** [comment]
It's done ;)
It's within the `epilog` of the `ArgumentParser` constructor:
https://github.com/patrickfuchs/buildH/blob/6c796618e1a5a8b3f31a45d65a690770fbd80d16/buildh/cli.py#L132-L134

```bash
$ buildH -h
[...]
  -e END, --end END     The last frame (ps) to read from the trajectory.
  -pi PICKLE, --pickle PICKLE
                        Output pickle filename. The structure pickled is a dictonnary containing for each Order
                        parameter, the value of each lipid and each frame as a matric

The list of supported lipids (-l option) are: CHARMM_POPC, Berger_POP, Berger_POPC, Berger_PLA.
```

**Comment by HubLot** [comment]
but the issue #44 is not done.

**Comment by patrickfuchs** [comment]
Oops sorry 😁... Great, so I can incorporate that into the first notebook. I checked the corresponding checkboxes up there.
So indeed, what is left to do is adding new lipids (#44). Almost there!

**Comment by patrickfuchs** [comment]
We close this issue since it's redundant with #44 at this stage.
