### ISSUE TITLE
Specify the type of trajectory supported

### ISSUE THREAD

**Issue by HubLot** [patrickfuchs/buildH#50]
Currently, we can support any trajectory and topology files that MDAnalysis support.
But, our argument option for trajectory is `-x, --xtc` wich implies that only xtc trajectory files are supported.

We should change it to a more general option name and specify it in the documentation

**Comment by patrickfuchs** [comment]
It has been specified in the help (`-h`) some commits ago. And it is now written in the doc as well: https://buildh.readthedocs.io/en/latest/command_line_options.html#output-trajectory. So I close this issue.
