### ISSUE TITLE
Generation of xtc with one frame?

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#53]
When the user provides a single pdb file without any trajectory (no use of `-x`), and the trajectory with H is requested with option `-opx`, buildH generates a pdb and an xtc. The xtc file contains only one frame, it's thus useless. Maybe we can check if `-x` is not used and `-opx` is used to generate only the pdb?

**Comment by HubLot** [comment]
Yes, we should check that.
