### ISSUE TITLE
Use mamba to create environement at Read the Docs

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#68]
The [feature flag](https://docs.readthedocs.io/en/stable/guides/feature-flags.html) `CONDA_USES_MAMBA` enables mamba instead of conda to create the environment at Read the Docs.

Unfortunately documentation is not very explicit on how to use feature flag...

**Comment by pierrepo** [comment]
OK. So we have to send an e-mail to the admin team:

https://twitter.com/JohanMabille/status/1357307519639642113

I'll handle it.

**Comment by pierrepo** [comment]
Mail sent.

**Comment by HubLot** [comment]
Great but is it necessary for our case? Can we try the regular conda and see how it goes?

**Comment by patrickfuchs** [comment]
Yeah, his name is speedypierrepo 🚤 !

**Comment by pierrepo** [comment]
>Great but is it necessary for our case? Can we try the regular conda and see how it goes?
Yes. Building conda env is always slow and we have quite some dependencies in `binder/requirements.yml`. Mamba is very useful here.

**Comment by pierrepo** [comment]
![image](https://user-images.githubusercontent.com/733861/106899493-b84ce580-66f5-11eb-9740-2ecf71f39bc1.png)

:tada:

**Comment by patrickfuchs** [comment]
yeah 🎆 !

**Comment by pierrepo** [comment]
For the record, e-mail of the request at support@readthedocs.org:
```
Dear Read the Docs admin team,

could you please activate this flag: CONDA_USES_MAMBA

to the repo https://readthedocs.org/projects/buildh/

for which I am a maintainer https://readthedocs.org/profiles/pierrepo/

Many thanks.

Regards.

Pierre


```

**Comment by pierrepo** [comment]
It's done.
Build time has been reduced from 852": https://readthedocs.org/projects/buildh/builds/12936203/
down to 586" : https://readthedocs.org/projects/buildh/builds/12937020/
