### ISSUE TITLE
Connect repo to Zenodo

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#72]
@patrickfuchs 
Could please connect the repo to Zendo with these [guidelines](https://guides.github.com/activities/citable-code/)?

Once done, can you try to publish a new release? Everything should be explained here: `buildH/devtools/RELEASE.md`

**Comment by pierrepo** [comment]
@patrickfuchs did you time to have a look?

**Comment by patrickfuchs** [comment]
No sorry... This week, I'm loaded with teaching duties and a GENCI application (deadling friday morning). I do my best to look at this ASAP, hopefully friday afternoon.

**Comment by patrickfuchs** [comment]
Done 😎! I have added the badge to `README.md`.
