### ISSUE TITLE
Refactorizing

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#8]
The main function `buildH_calcOP.py`  gets big. It would be nice to refactorize it by adding functions.
Also, the script `buildH_calcOP.py` could be factorized by adding modules.

**Comment by HubLot** [comment]
I started the refactorizing and the slipt into modules in that branch : https://github.com/HubLot/buildH/tree/modules

**Comment by patrickfuchs** [comment]
We're almost there after @HubLot's last PR. Next week I do my best to finalize this issue.

**Comment by patrickfuchs** [comment]
Thanks to #22 we can close this one.
