### ISSUE TITLE
Getting rid of MDAnalysis warnings

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#86]
When launching **buildH** many MDAnalysis warnings pollute the output :

```
$ buildH -c PO3C.pdb -d Berger_PO3C_POC3.def -l Berger_PO3C -lt Berger_PO3C.json -opx PO3C_wH
Constructing the system...
/home/fuchs/software/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/topology/PDBParser.py:330: UserWarning: Element information is absent or missing for a few atoms. Elements attributes will not be populated.
  warnings.warn("Element information is absent or missing for a few "
/home/fuchs/software/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/topology/base.py:203: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  residx = np.zeros_like(criteria[0], dtype=np.int)
/home/fuchs/software/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/core/selection.py:521: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask = np.zeros(len(group), dtype=np.bool)
System has 3 atoms
Writing new pdb with hydrogens.
/home/fuchs/software/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/topology/PDBParser.py:330: UserWarning: Element information is absent or missing for a few atoms. Elements attributes will not be populated.
  warnings.warn("Element information is absent or missing for a few "
/home/fuchs/software/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/topology/base.py:203: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  residx = np.zeros_like(criteria[0], dtype=np.int)
/home/fuchs/software/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/core/selection.py:521: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask = np.zeros(len(group), dtype=np.bool)
/home/fuchs/software/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/coordinates/base.py:865: UserWarning: Reader has no dt information, set to 1.0 ps
  warnings.warn("Reader has no dt information, set to 1.0 ps")
Dealing with frame 0 at 0.0 ps.
Results written to OP_buildH.out
```

It's very confusing and I find difficult to extract what is the real **buildH** output. That'd be nice to get rid of these warnings, I guess it's doable but don't know how to do that. Any idea?

**Comment by HubLot** [comment]
Here, you have both MDAnalysis warnings and Numpy ones in the MDA package :)

We can ignore at least the MDA ones  by using (I guess in the `__init__.py`)
```python
import warnings
warnings.filterwarnings("ignore", message="Element information [...]"
```

**Comment by patrickfuchs** [comment]
Excellent, thanks @HubLot 👍 For the MDA ones, I guess they come from a non-standard PDB or no time info, thus they can be safely ignored. For the Numpy ones, they are about deprecated functions, maybe we can try to fix those?

**Comment by HubLot** [comment]
> For the Numpy ones, they are about deprecated functions, maybe we can try to fix those?
No, the warnings are in the MDA package, it is up to them to fix those.

**Comment by patrickfuchs** [comment]
OK in this case, I suggest to make all these warnings silent as you suggest 😄 !

**Comment by pierrepo** [comment]
Hello @patrickfuchs and @HubLot
Is this issue fixed?

**Comment by patrickfuchs** [comment]
Not yet! @HubLot & @pierrepo could you please test buildH on a simple traj and tell me whether you get those warnings? I'm wondering if they come from my old version of Ubuntu.

**Comment by pierrepo** [comment]
I did not find `PO3C.pdb`, `Berger_PO3C_POC3.def` and `Berger_PO3C.json` files in the repo.
You could please include them in the repo? Maybe in `docs/Berger_PO3C_test_case`?

**Comment by patrickfuchs** [comment]
> I did not find `PO3C.pdb`, `Berger_PO3C_POC3.def` and `Berger_PO3C.json` files in the repo.
> You could please include them in the repo? Maybe in `docs/Berger_PO3C_test_case`?

In fact PO3C molecule was a dummy molecule I used for making figures for the doc 😉 I get these warnings on any traj, so you can test for example the [POPC beger test case](https://github.com/patrickfuchs/buildH/tree/master/docs/Berger_POPC_test_case) (you'll need start_128popc.pdb, popc0-25ns_dt1000.xtc & order_parameter_definitions_MODEL_Berger_POPC.def). Thanks!

**Comment by pierrepo** [comment]
Here's the output I got:
```
$ buildH -c docs/Berger_POPC_test_case/start_128popc.pdb -t docs/Berger_POPC_test_case/popc0-25ns_dt1000.xtc -d docs/Berger_POPC_test_case/order_parameter_definitions_MODEL_Berger_POPC.def -l Berger_POPC
Constructing the system...
/home/pierre/.soft/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/topology/PDBParser.py:330: UserWarning: Element information is absent or missing for a few atoms. Elements attributes will not be populated.
  warnings.warn("Element information is absent or missing for a few "
/home/pierre/.soft/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/topology/base.py:203: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  residx = np.zeros_like(criteria[0], dtype=np.int)
/home/pierre/.soft/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/core/selection.py:521: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask = np.zeros(len(group), dtype=np.bool)
System has 28526 atoms
Dealing with frame 0 at 0.0 ps.
Dealing with frame 1 at 1000.0 ps.
/home/pierre/.soft/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/core/selection.py:521: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask = np.zeros(len(group), dtype=np.bool)
Dealing with frame 2 at 2000.0 ps.
Dealing with frame 3 at 3000.0 ps.
[...]
Dealing with frame 24 at 24000.0 ps.
Dealing with frame 25 at 25000.0 ps.
Results written to OP_buildH.out
```

**Comment by patrickfuchs** [comment]
Thanks @pierrepo. Looks like these warnings appear always, so we should implement @HubLot 's suggestion. I'm not sure what to put in the argument `message=` in the call of `warnings.filterwarnings("ignore", message="Element information [...]"`. @HubLot, did you try this out?

**Comment by HubLot** [comment]
You should put the whole string of the Warning message, i.e `Element information is absent or missing for a few `

**Comment by patrickfuchs** [comment]
Thanks. And for the ones like `Deprecated in NumPy 1.20` ?

**Comment by HubLot** [comment]
Not our concern :D

**Comment by patrickfuchs** [comment]
> Not our concern :D

Well it pollutes the output, that'd be nice if we could getting rid of them, even if we're not responsible!

**Comment by HubLot** [comment]
I know but it's warnings of numpy about MDA. 
If we silent them (numpy warnings), it would affect also buildh and could have side effects :(

**Comment by patrickfuchs** [comment]
In this case, MDAnalsysis warnings may have side effects too... One other solution, we don't silent any warning but we explain in the documentation (notebooks) that is not our fault? And we could suggest, if wanted, it's possible to trash them like that: `buildH blablabla 2> /dev/null`

**Comment by HubLot** [comment]
> In this case, MDAnalsysis warnings may have side effects too... 

True but by specifying the message, we will only ignore the one "Element information[...]"  which we can agree is safe to ignore.
Plus, people with a full 'correct' PDB don't see this warning.

> One other solution, we don't silent any warning but we explain in the documentation (notebooks) that is not our fault? And we > could suggest, if wanted, it's possible to trash them like that: `buildH blablabla 2> /dev/null`

Yes why not, I'll put this in the `additional section` of the doc and stating that it's only occurs on numpy >= 1.20. We will remove it once it's has been took care at the MDA side.

**Comment by patrickfuchs** [comment]
> True but by specifying the message, we will only ignore the one "Element information[...]" which we can agree is safe to ignore.
> Plus, people with a full 'correct' PDB don't see this warning.

This one is not important and could be made silent for sure. But I'm thinking some future warnings may be important? We cannot know...

> Yes why not, I'll put this in the `additional section` of the doc and stating that it's only occurs on numpy >= 1.20. We will remove it once it's has been took care at the MDA side.

You mean you will do it? If not, I can take care of that. And yes, `additional section` is a good place.

**Comment by HubLot** [comment]
i'm on it

**Comment by patrickfuchs** [comment]
In principle, PR #121 should have closed this issue, so I do it manually.
