### ISSUE TITLE
Be more explicit on error message

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#96]
I recently encountered this error message:

```
Some carbons (N4) from the definition file are notpresent in the topology chosen.
Atoms defined in order_parameter_definitions_MODEL_Berger_POPE.def are not consistent with the chosen topology.
```

I found it not very clear. First the word `topology` is not defined. If we want to use that word, we should define it in the doc. But I'd be rather more explicit and say that there is merely a mismatch between the pdb (or gro) file and the def file.

Initially, this was a first try with Berger POPE. The culprit lines were:

```
gamma1 POPE N4  H11
gamma2 POPE N4  H12
gamma3 POPE N4  H13
```

while the pdb was:

```
ATOM   6657  H1  POPE  129      82.600  -2.110  24.640  1.00 0.00
ATOM   6658  H2  POPE  129      82.290  -1.570  23.100  1.00 0.00
ATOM   6659  H3  POPE  129      83.140  -0.610  24.130  1.00 0.00
ATOM   6660  N4  POPE  129      82.400  -1.300  24.070  1.00 0.00
```

So here I first thought it was coming from atoms H11, H12 and H13 that do not exist in the pdb. I think that'd be nice to be more explicit and include the hydrogen names (not only the carbon name) in the error message.

Next, I got another problem. By correcting the def file with:

```
gamma1 POPE N4  H1
gamma2 POPE N4  H2
gamma3 POPE N4  H3
```

I still got that error message:

```
Some carbons (N4) from the definition file are notpresent in the topology chosen.
Atoms defined in order_parameter_definitions_MODEL_Berger_POPE.def are not consistent with the chosen topology.
```

Initially I was confused because all atoms names were well defined. In fact, the pb was that I had defined N-H bonds but **buildH** only works with C-H bonds!!! OK that is fine to make **buildH** work only on C-H bonds. But in this case the error was different from the first. So I'd suggest to change the error message if possible.

**Comment by HubLot** [comment]
The error message is in fact due to a mismatch between the def file and the json file (hence the word _topology_ for the json file).
It says `"Some atoms (N4)"`. Here, it seems the **N4** atom is not present in the json file.
Do you have a json file for the POPE ?

I agree we can be more explicit with this message (specially since we can treat nitrogen also, it just depends on the json file.

**Comment by patrickfuchs** [comment]
> The error message is in fact due to a mismatch between the def file and the json file (hence the word _topology_ for the json file).
> It says `"Some atoms (N4)"`. Here, it seems the **N4** atom is not present in the json file.

OK, so I'd prefer `Some atoms (N4) from the definition file are not present in the json file.` 😉 

> Do you have a json file for the POPE ?

Sure!

> I agree we can be more explicit with this message (specially since we can treat nitrogen also, it just depends on the json file.

Well I don't know if we need to add N-H. I'm not sure we can have 2H NMR data because those deuterons are exchangeable.

**Comment by HubLot** [comment]
> 
> 
> > The error message is in fact due to a mismatch between the def file and the json file (hence the word _topology_ for the json file).
> > It says `"Some atoms (N4)"`. Here, it seems the **N4** atom is not present in the json file.
> 
> OK, so I'd prefer `Some atoms (N4) from the definition file are not present in the json file.` 😉

okay !

> 
> > I agree we can be more explicit with this message (specially since we can treat nitrogen also, it just depends on the json file.
> 
> Well I don't know if we need to add N-H. I'm not sure we can have 2H NMR data because those deuterons are exchangeable.

Okay, you're right.

But what was the error at the end ? A bad json ?
Because it don't check whether it's a Carbon or Nitrogen, only if the def and json matches

**Comment by patrickfuchs** [comment]
> But what was the error at the end ? A bad json ?
> Because it don't check whether it's a Carbon or Nitrogen, only if the def and json matches

Correct! The start of the json file was:

```
{
  "resname": ["POPE"],
  "C5": ["CH2", "N4", "C6"],
  "C6": ["CH2", "C5", "O7"],
  "C12": ["CH2", "O11", "C13"],
[...]
```

There's no line starting with `"N4"`, hence the error. But indeed, with one extra line ` "N4": ["CH2", "C5", "C6"],`, it would have worked 😉 !
