### ISSUE TITLE
Register buildH to bio.tools

### ISSUE THREAD

**Issue by pierrepo** [patrickfuchs/buildH#97]
[Bio.tools](https://bio.tools/) is a registry for software and databases used in life sciences. This registry is maintained by Elixir.

We should register buildH to bio.tools.

@HubLot and @patrickfuchs could you please [create an account](https://bio.tools/signup) in the bio.tools user portal and provide me your username?

**Comment by patrickfuchs** [comment]
I just signed in, my user name is `patrickfuchs`.

**Comment by HubLot** [comment]
Mine is `HubLot`

**Comment by pierrepo** [comment]
All set: https://bio.tools/buildh
